/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.mina.transport.nio;

import java.io.IOException;
import java.nio.ByteBuffer;

/**
 * Listener for I/O events generated by {@link NioSelectorProcessor}.
 * 
 * @author <a href="http://mina.apache.org">Apache MINA Project</a>
 */
public interface SelectorEventListener {

    /**
     * A read ready event
     * @param processor the processor generating this event
     * @param readBuffer the buffer to be used for reading
     */
    void readReady(NioSelectorProcessor processor, ByteBuffer readBuffer) throws IOException;

    /**
     * A write ready event
     * @param processor the processor generating this event
     */
    void writeReady(NioSelectorProcessor processor) throws IOException;

    /**
     * An accept ready event
     * @param processor the processor generating this event
     */
    void acceptReady(NioSelectorProcessor processor) throws IOException;
}
